export const LOAD_CATALOGS_INFO = 'LOAD_CATALOGS_INFO';
export const CATALOGS_INFO_LOADED = 'CATALOGS_INFO_LOADED';
//
export const LOAD_CATALOG_OFFERS = 'LOAD_CATALOG_OFFERS';
export const CATALOG_OFFERS_LOADED = 'CATALOG_OFFERS_LOADED';
//
